<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HerMemory</AssemblyName>
    <RootNamespace>HerMemory</RootNamespace>
    <Version>0.1.0</Version>
    <Product>HerMemory</Product>
    <AssemblyTitle>HerMemory 安装向导</AssemblyTitle>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
